### PR TITLE
fixes Content-Length after content change

### PR DESCRIPTION
**Pull request by seroy**
With Django 1.7.x and django-htmlmin fails with infinity loop

### CODE REVIEW

**Comment by andrewsmedina** [comment]
hi @seroy thanks for contribute, can you add a test?

**Comment by seroy** [comment]
Completed!

Some comments:
If the response has a Content-Length header (for example Django ConditionalGetMiddleware sets this header), HtmlMinifyMiddleware should modify this when it modifies the response body. Otherwise the browser might truncate the response and produce a broken page or (in my case) might try to repeat request until don't receives content with lenght as expected in header (in other words infinitely).

**Comment by andrewsmedina** [comment]
@seroy this comment should be docummented?

**Comment by lockie** [comment]
Hi!
It would be lovely to merge this, as without this fix there is obscure Django error, e.g. using curl:
```
transfer closed with 4425 bytes remaining to read
```

**Comment by andrewsmedina** [comment]
This PR is duplicated of https://github.com/cobrateam/django-htmlmin/pull/122

**Pull request closed without merging**
